/**
 * Synthetic traffic generator — SPEC §8.
 *
 *   npm run seed -- --sessions=150 --seed=42 --target=http://localhost:3000
 *
 * Drives the real HTTP API only (`POST /api/session`, `/api/session/answer`,
 * `/api/session/back`, `/api/events`). No database access, never touches admin
 * routes: sessions land on whatever version is active, and the materialised config
 * returned by `POST /api/session` is walked exactly as the UI would, so any version
 * works with no code change. Every session is created with the `x-synthetic: 1`
 * header, so it and its events are stored with is_synthetic = 1.
 *
 * Reproducibility. Every decision (campaign, answers, drop-off, back-navigation,
 * CTA clicks, batching, adversarial cases) comes from a mulberry32 PRNG derived from
 * `--seed` and the session's index, so decisions do not depend on concurrency.
 * Session IDs, however, are generated by the server, and variant assignment hashes
 * the session ID — so the A/B split (and therefore which step order each session
 * walks) varies slightly between runs even with the same seed.
 *
 * Event IDs are valid v4 UUIDs built from PRNG bytes, seeded from `--seed` plus the
 * server-issued session ID. Seeding them from `--seed` alone would make a second run
 * (e.g. after activating v3, §11) re-send the first run's event IDs, and every one of
 * them would be dropped as a duplicate.
 *
 * Adversarial cases, all present in a default run: duplicate event_ids within a
 * batch, one batch re-sent verbatim, shuffled batches with skewed client_ts,
 * schema-invalid items, a client-sent session_started, an unknown session, and
 * recommendation_expanded on CTA clicks (accepted on v3, rejected on v1).
 *
 * Exits 1 if any invariant in the summary fails.
 */
import { pathToFileURL } from 'node:url';
import {
  REJECT_REASONS,
  SESSION_COOKIE,
  SYNTHETIC_HEADER,
  type EventBatchResponse,
  type EventResult,
  type NavigationResponse,
  type RejectReason,
  type SessionResponse,
} from '@shared/api';
import type { AnswerValue, MaterialisedConfig, Step } from '@shared/types';

// ---------------------------------------------------------------------------
// Options
// ---------------------------------------------------------------------------

interface Options {
  sessions: number;
  seed: number;
  target: string;
  concurrency: number;
}

export function parseArgs(argv: string[]): Options {
  const options: Options = { sessions: 150, seed: 42, target: 'http://localhost:3000', concurrency: 6 };
  for (const arg of argv) {
    const match = /^--([a-z]+)=(.+)$/.exec(arg);
    if (!match) throw new Error(`Unrecognised argument "${arg}". Usage: --sessions=150 --seed=42 --target=http://localhost:3000`);
    const [, key, value] = match;
    if (key === 'target') {
      options.target = new URL(value).origin;
    } else if (key === 'sessions' || key === 'seed' || key === 'concurrency') {
      const n = Number(value);
      if (!Number.isInteger(n) || n < (key === 'seed' ? 0 : 1)) throw new Error(`--${key} must be an integer${key === 'seed' ? ' >= 0' : ' >= 1'}`);
      options[key] = n;
    } else {
      throw new Error(`Unknown option --${key}`);
    }
  }
  return options;
}

// ---------------------------------------------------------------------------
// Seeded randomness
// ---------------------------------------------------------------------------

export type Rng = () => number;

export function mulberry32(seed: number): Rng {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = a;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

export function fnv1a(text: string): number {
  let hash = 0x811c9dc5;
  for (let i = 0; i < text.length; i++) {
    hash ^= text.charCodeAt(i);
    hash = Math.imul(hash, 0x01000193);
  }
  return hash >>> 0;
}

/** Decisions for session #index depend only on (seed, index). */
export const sessionRng = (seed: number, index: number): Rng => mulberry32(fnv1a(`session:${seed}:${index}`));

const int = (rng: Rng, min: number, max: number): number => min + Math.floor(rng() * (max - min + 1));
const chance = (rng: Rng, p: number): boolean => rng() < p;

function weightedIndex(rng: Rng, weights: number[]): number {
  const total = weights.reduce((sum, w) => sum + w, 0);
  let roll = rng() * total;
  for (let i = 0; i < weights.length; i++) {
    roll -= weights[i];
    if (roll < 0) return i;
  }
  return weights.length - 1;
}

function shuffle<T>(rng: Rng, items: T[]): T[] {
  const copy = [...items];
  for (let i = copy.length - 1; i > 0; i--) {
    const j = Math.floor(rng() * (i + 1));
    [copy[i], copy[j]] = [copy[j], copy[i]];
  }
  return copy;
}

/** RFC 4122 v4 UUID from 16 PRNG bytes (version nibble 4, variant bits 10xx). */
export function uuidFromBytes(bytes: number[]): string {
  const b = [...bytes];
  b[6] = (b[6] & 0x0f) | 0x40;
  b[8] = (b[8] & 0x3f) | 0x80;
  const hex = b.map((x) => x.toString(16).padStart(2, '0')).join('');
  return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-${hex.slice(12, 16)}-${hex.slice(16, 20)}-${hex.slice(20, 32)}`;
}

/**
 * Event-ID stream for one session. Two independent 32-bit streams feed the two
 * halves of the UUID, so IDs from different sessions only collide if both hashes do.
 */
export function eventIdGenerator(seed: number, sessionId: string): () => string {
  const high = mulberry32(fnv1a(`ids-high:${seed}:${sessionId}`));
  const low = mulberry32(fnv1a(`ids-low:${seed}:${sessionId}`));
  const byte = (rng: Rng) => Math.floor(rng() * 256);
  return () => uuidFromBytes([...Array.from({ length: 8 }, () => byte(high)), ...Array.from({ length: 8 }, () => byte(low))]);
}

// ---------------------------------------------------------------------------
// Traffic model
// ---------------------------------------------------------------------------

type Utm = { utm_source: string; utm_medium: string; utm_campaign: string };

const CAMPAIGNS: { weight: number; utm: Utm | null }[] = [
  { weight: 28, utm: { utm_source: 'google', utm_medium: 'cpc', utm_campaign: 'spring_launch' } },
  { weight: 20, utm: { utm_source: 'newsletter', utm_medium: 'email', utm_campaign: 'newsletter_q2' } },
  { weight: 14, utm: { utm_source: 'partner', utm_medium: 'referral', utm_campaign: 'partner_webinar' } },
  { weight: 20, utm: { utm_source: 'linkedin', utm_medium: 'paid_social', utm_campaign: 'linkedin_ops' } },
  { weight: 18, utm: null },
];

/** Single-select weights by step ID; unlisted steps/options are uniform. */
const SINGLE_SELECT_WEIGHTS: Record<string, Record<string, number>> = {
  work_mode: { remote: 40, hybrid: 40, office: 20 },
};

/** 5–12% per step, fixed per step ID so drop-off is spread across steps. */
export const abandonProbability = (stepId: string): number => 0.05 + (fnv1a(`abandon:${stepId}`) % 8) / 100;

const BACK_PROBABILITY = 0.12;
const CTA_PROBABILITY = 0.55;

export function pickAnswer(step: Step, rng: Rng): AnswerValue | undefined {
  const options = (step.input?.options ?? []).map((o) => o.value);
  switch (step.type) {
    case 'single-select': {
      if (options.length === 0) return undefined;
      const weights = options.map((o) => SINGLE_SELECT_WEIGHTS[step.id]?.[o] ?? 1);
      return options[weightedIndex(rng, weights)];
    }
    case 'multi-select': {
      const min = Math.max(1, step.validation?.minSelections ?? 1);
      const max = Math.max(min, Math.min(3, step.validation?.maxSelections ?? 3, options.length));
      const count = int(rng, min, max);
      const picked: string[] = [];
      if (options.includes('compliance') && chance(rng, 0.3)) picked.push('compliance');
      const pool = options.filter((o) => o !== 'compliance');
      while (picked.length < count && pool.length > 0) picked.push(pool.splice(Math.floor(rng() * pool.length), 1)[0]);
      return picked;
    }
    case 'number': {
      const min = typeof step.input?.min === 'number' ? step.input.min : 0;
      const max = typeof step.input?.max === 'number' ? step.input.max : min + 10;
      const increment = typeof step.input?.step === 'number' && step.input.step > 0 ? step.input.step : 1;
      let lo = min;
      let hi = max;
      if (step.id === 'meeting_hours') {
        if (chance(rng, 0.35)) lo = Math.max(min, 15);
        else hi = Math.min(max, 14);
      }
      const kLo = Math.ceil((lo - min) / increment);
      const kHi = Math.floor((hi - min) / increment);
      return kHi < kLo ? min : min + int(rng, kLo, kHi) * increment;
    }
    default:
      return undefined; // info, and unknown types rendered as skip-able placeholders
  }
}

// ---------------------------------------------------------------------------
// HTTP
// ---------------------------------------------------------------------------

class HttpError extends Error {}

/** One per simulated browser: carries that session's cookie jar. */
class ApiClient {
  private cookie: string | null = null;

  constructor(private readonly target: string) {}

  async post<T>(path: string, body?: unknown): Promise<T> {
    const headers: Record<string, string> = { [SYNTHETIC_HEADER]: '1' };
    if (this.cookie) headers.cookie = this.cookie;
    let payload: string | undefined;
    if (body !== undefined) {
      headers['content-type'] = 'application/json';
      payload = JSON.stringify(body);
    }
    const response = await fetch(new URL(path, this.target), { method: 'POST', headers, body: payload });
    const sessionCookie = response.headers
      .getSetCookie()
      .map((c) => c.split(';')[0].trim())
      .find((c) => c.startsWith(`${SESSION_COOKIE}=`));
    if (sessionCookie) this.cookie = sessionCookie;
    const text = await response.text();
    if (!response.ok) throw new HttpError(`POST ${path} -> ${response.status}: ${text.slice(0, 300)}`);
    return JSON.parse(text) as T;
  }
}

// ---------------------------------------------------------------------------
// Tally
// ---------------------------------------------------------------------------

const increment = <K>(map: Map<K, number>, key: K, by = 1) => map.set(key, (map.get(key) ?? 0) + by);

interface Tally {
  sessionsCreated: number;
  failures: string[];
  versions: Map<number, number>;
  variants: Map<string, number>;
  campaigns: Map<string, number>;
  reachedResult: number;
  abandonedAt: Map<string, number>;
  workModes: Map<string, number>;
  backClicks: number;
  ctaClicks: number;
  batches: number;
  shuffledBatches: number;
  sent: number;
  accepted: number;
  duplicate: number;
  rejected: Map<RejectReason, number>;
  non200: string[];
  misaligned: string[];
  injectedInvalid: number;
  injectedDuplicates: number;
  injectedServerOnly: number;
  injectedUnknownSession: number;
  resend: { done: boolean; accepted: number; unexpected: number };
}

const newTally = (): Tally => ({
  sessionsCreated: 0,
  failures: [],
  versions: new Map(),
  variants: new Map(),
  campaigns: new Map(),
  reachedResult: 0,
  abandonedAt: new Map(),
  workModes: new Map(),
  backClicks: 0,
  ctaClicks: 0,
  batches: 0,
  shuffledBatches: 0,
  sent: 0,
  accepted: 0,
  duplicate: 0,
  rejected: new Map(REJECT_REASONS.map((r) => [r, 0])),
  non200: [],
  misaligned: [],
  injectedInvalid: 0,
  injectedDuplicates: 0,
  injectedServerOnly: 0,
  injectedUnknownSession: 0,
  resend: { done: false, accepted: 0, unexpected: 0 },
});

// ---------------------------------------------------------------------------
// One session
// ---------------------------------------------------------------------------

interface WireEvent {
  event_id: string;
  session_id: string;
  name: string;
  step_id: string | null;
  client_ts: string;
  props: Record<string, unknown>;
}

/** Items the walk produced that must come back accepted (first copy) / duplicate (later copies). */
const DUPLICATE_SAFE = new Set(['step_viewed', 'answer_submitted', 'step_completed', 'back_clicked', 'result_viewed', 'cta_clicked']);

const INVALID_KINDS: ((template: WireEvent) => unknown)[] = [
  (e) => ({ ...e, event_id: 'not-a-uuid' }),
  (e) => ({ ...e, name: undefined }),
  (e) => ({ ...e, props: 'answer_kind=number' }),
  (e) => ({ ...e, session_id: 12345 }),
  () => 'garbage',
  (e) => ({ ...e, step_id: { nested: true } }),
  () => null,
];

async function sendBatch(target: string, body: string): Promise<{ status: number; results: EventResult[] | null; text: string }> {
  const response = await fetch(new URL('/api/events', target), {
    method: 'POST',
    headers: { 'content-type': 'application/json', [SYNTHETIC_HEADER]: '1' },
    body,
  });
  const text = await response.text();
  if (response.status !== 200) return { status: response.status, results: null, text };
  return { status: 200, results: (JSON.parse(text) as EventBatchResponse).results, text };
}

async function runSession(index: number, options: Options, tally: Tally): Promise<void> {
  const rng = sessionRng(options.seed, index);
  const campaign = CAMPAIGNS[weightedIndex(rng, CAMPAIGNS.map((c) => c.weight))];
  const client = new ApiClient(options.target);

  const query = campaign.utm ? `?${new URLSearchParams(campaign.utm)}` : '';
  const created = await client.post<SessionResponse>(`/api/session${query}`);
  tally.sessionsCreated++;
  increment(tally.versions, created.funnelVersion);
  increment(tally.variants, created.variant);
  increment(tally.campaigns, campaign.utm?.utm_campaign ?? '(none)');

  const config: MaterialisedConfig = created.config;
  const nextEventId = eventIdGenerator(options.seed, created.sessionId);
  const events: WireEvent[] = [];
  let clock = Date.now() - int(rng, 10 * 60, 6 * 3600) * 1000;
  const emit = (name: string, stepId: string | null, props: Record<string, unknown>) => {
    clock += int(rng, 2, 9) * 1000;
    events.push({ event_id: nextEventId(), session_id: created.sessionId, name, step_id: stepId, client_ts: new Date(clock).toISOString(), props });
  };

  let nav: NavigationResponse = created;
  const stepViewed = () => {
    const id = nav.currentStepId;
    if (!id) return;
    emit('step_viewed', id, {
      step_type: config.steps[id]?.type ?? 'unknown',
      visible_step_index: nav.visibleSteps.indexOf(id) + 1,
      visible_step_count: nav.visibleSteps.length,
    });
  };

  // Walk the funnel as the UI would: render, answer, render what the server returns.
  try {
    stepViewed();
    let backs = 0;
    for (let guard = 0; guard < 200 && nav.currentStepId; guard++) {
      const stepId: string = nav.currentStepId;
      const step: Step = config.steps[stepId] ?? { id: stepId, type: 'unknown' };

      if (step.type === 'result') {
        tally.reachedResult++;
        emit('result_viewed', stepId, {});
        if (chance(rng, CTA_PROBABILITY)) {
          tally.ctaClicks++;
          const action = config.results[nav.resultId ?? '']?.cta?.action ?? 'expand_recommendation';
          emit('cta_clicked', stepId, { action });
          // Emitted regardless of the allowed list: accepted on v3, rejected on v1.
          emit('recommendation_expanded', stepId, { action, source: 'cta' });
        }
        break;
      }

      if (chance(rng, abandonProbability(stepId))) {
        increment(tally.abandonedAt, stepId);
        break;
      }

      const value = pickAnswer(step, rng);
      if (stepId === 'work_mode' && typeof value === 'string') increment(tally.workModes, value);
      const answered = await client.post<NavigationResponse>('/api/session/answer', value === undefined ? { stepId } : { stepId, value });
      if (answered.currentStepId === stepId) throw new Error(`server did not advance from "${stepId}" (answer ${JSON.stringify(value)})`);
      if (step.type !== 'info') emit('answer_submitted', stepId, { answer_kind: step.type });
      emit('step_completed', stepId, { next_step_id: answered.currentStepId });
      nav = answered;
      stepViewed();

      const here = nav.currentStepId;
      if (here && config.steps[here]?.type !== 'result' && backs < 3 && chance(rng, BACK_PROBABILITY)) {
        const back = await client.post<NavigationResponse>('/api/session/back', { stepId: here });
        backs++;
        tally.backClicks++;
        emit('back_clicked', here, { destination_step_id: back.currentStepId });
        nav = back;
        stepViewed();
      }
    }
  } catch (err) {
    // Still send what was collected: the events up to the failure are real.
    tally.failures.push(`session #${index} (${created.sessionId}): ${(err as Error).message}`);
  }

  // Adversarial items mixed into the otherwise valid stream.
  const items: unknown[] = [...events];
  const duplicateSafe = new Set<unknown>(events.filter((e) => DUPLICATE_SAFE.has(e.name)));
  const insertAt = (item: unknown) => items.splice(int(rng, 0, items.length), 0, item);
  const template = events[0];
  if (template) {
    if (index < 6 || chance(rng, 0.03)) {
      insertAt(INVALID_KINDS[index % INVALID_KINDS.length]({ ...template, event_id: nextEventId() }));
      tally.injectedInvalid++;
    }
    if (index % 50 === 0) {
      insertAt({ ...template, event_id: nextEventId(), name: 'session_started', step_id: null, props: {} });
      tally.injectedServerOnly++;
    }
    if (index % 50 === 3) {
      insertAt({ ...template, event_id: nextEventId(), session_id: uuidFromBytes(Array.from({ length: 16 }, () => int(rng, 0, 255))) });
      tally.injectedUnknownSession++;
    }
  }

  // Split into 1–3 contiguous batches.
  const batchCount = Math.min(items.length, int(rng, 1, 3));
  const cuts = shuffle(rng, Array.from({ length: Math.max(0, items.length - 1) }, (_, i) => i + 1))
    .slice(0, batchCount - 1)
    .sort((a, b) => a - b);
  const bounds = [0, ...cuts, items.length];

  let firstBatch: { body: string; results: EventResult[] } | null = null;
  for (let b = 0; b < bounds.length - 1; b++) {
    let batch = items.slice(bounds[b], bounds[b + 1]);

    if ((index === 0 && b === 0) || chance(rng, 0.2)) {
      const candidates = batch.filter((item) => duplicateSafe.has(item));
      const copies = Math.min(candidates.length, int(rng, 1, 2));
      for (const original of shuffle(rng, candidates).slice(0, copies)) {
        batch.splice(int(rng, batch.indexOf(original) + 1, batch.length), 0, original);
        tally.injectedDuplicates++;
      }
    }

    if ((index === 2 && b === 0) || chance(rng, 0.15)) {
      const skewMs = (chance(rng, 0.5) ? 1 : -1) * int(rng, 1, 10) * 60_000;
      batch = shuffle(
        rng,
        batch.map((item) => (duplicateSafe.has(item) ? { ...(item as WireEvent), client_ts: new Date(Date.parse((item as WireEvent).client_ts) + skewMs).toISOString() } : item)),
      );
      tally.shuffledBatches++;
    }

    const body = JSON.stringify({ events: batch });
    const results = await deliver(options.target, body, batch, tally, `session #${index} batch ${b + 1}`);
    if (b === 0 && results) firstBatch = { body, results };
  }

  // One entire batch re-sent verbatim, as a client retrying after a timeout would.
  if (index === 0 && firstBatch) {
    const parsed = (JSON.parse(firstBatch.body) as { events: unknown[] }).events;
    const results = await deliver(options.target, firstBatch.body, parsed, tally, `session #${index} verbatim resend`);
    tally.resend.done = results !== null;
    if (results) {
      results.forEach((result, i) => {
        if (result.status === 'accepted') tally.resend.accepted++;
        const expected = firstBatch.results[i]?.status === 'rejected' ? 'rejected' : 'duplicate';
        if (result.status !== expected) tally.resend.unexpected++;
      });
    }
  }
}

async function deliver(target: string, body: string, batch: unknown[], tally: Tally, label: string): Promise<EventResult[] | null> {
  tally.batches++;
  tally.sent += batch.length;
  const response = await sendBatch(target, body);
  if (response.status !== 200 || !response.results) {
    tally.non200.push(`${label}: HTTP ${response.status} ${response.text.slice(0, 200)}`);
    return null;
  }
  const { results } = response;
  const aligned =
    results.length === batch.length &&
    results.every((result, i) => {
      const item = batch[i] as { event_id?: unknown } | null;
      const sentId = typeof item === 'object' && item !== null && typeof item.event_id === 'string' ? item.event_id : null;
      return result.event_id === sentId;
    });
  if (!aligned) tally.misaligned.push(`${label}: ${results.length} results for ${batch.length} items`);
  for (const result of results) {
    if (result.status === 'accepted') tally.accepted++;
    else if (result.status === 'duplicate') tally.duplicate++;
    else increment(tally.rejected, result.reason ?? ('unknown' as RejectReason));
  }
  return results;
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

const formatMap = <K>(map: Map<K, number>): string =>
  map.size === 0 ? '(none)' : [...map].map(([k, v]) => `${String(k)}: ${v}`).join(', ');

async function main(): Promise<void> {
  let options: Options;
  try {
    options = parseArgs(process.argv.slice(2));
  } catch (err) {
    console.error((err as Error).message);
    process.exit(2);
  }

  console.log(`Seeding ${options.sessions} sessions against ${options.target} (seed ${options.seed}, concurrency ${options.concurrency})`);
  const tally = newTally();
  const started = Date.now();

  let next = 0;
  const worker = async () => {
    while (next < options.sessions) {
      const index = next++;
      try {
        await runSession(index, options, tally);
      } catch (err) {
        tally.failures.push(`session #${index}: ${(err as Error).message}`);
      }
      const done = index + 1;
      if (done % 25 === 0) console.log(`  ${done} sessions started`);
    }
  };
  await Promise.all(Array.from({ length: Math.min(options.concurrency, options.sessions) }, worker));

  const rejectedTotal = [...tally.rejected.values()].reduce((a, b) => a + b, 0);
  const pct = (n: number, d: number) => (d === 0 ? 'n/a' : `${((100 * n) / d).toFixed(1)}%`);

  console.log(`\nSummary (${((Date.now() - started) / 1000).toFixed(1)}s)`);
  console.log(`  sessions created    ${tally.sessionsCreated} / ${options.sessions}`);
  console.log(`  versions            ${formatMap(tally.versions)}`);
  console.log(`  variants            ${formatMap(tally.variants)}`);
  console.log(`  utm campaigns       ${formatMap(tally.campaigns)}`);
  console.log(`  work_mode answers   ${formatMap(tally.workModes)}`);
  console.log(`  reached result      ${tally.reachedResult} (${pct(tally.reachedResult, tally.sessionsCreated)})`);
  console.log(`  abandoned at        ${formatMap(tally.abandonedAt)}`);
  console.log(`  back navigations    ${tally.backClicks}`);
  console.log(`  cta clicks          ${tally.ctaClicks}`);
  console.log(`  batches sent        ${tally.batches} (${tally.shuffledBatches} shuffled + skewed, ${tally.resend.done ? 1 : 0} verbatim resend)`);
  console.log(`  events sent         ${tally.sent}`);
  console.log(`    accepted          ${tally.accepted}`);
  console.log(`    duplicate         ${tally.duplicate}`);
  console.log(`    rejected          ${rejectedTotal} (${formatMap(tally.rejected)})`);
  console.log(
    `  injected            ${tally.injectedInvalid} invalid, ${tally.injectedDuplicates} duplicate copies, ` +
      `${tally.injectedServerOnly} client session_started, ${tally.injectedUnknownSession} unknown session`,
  );
  if (tally.failures.length) console.log(`  failures\n    ${tally.failures.slice(0, 20).join('\n    ')}`);
  if (tally.non200.length) console.log(`  non-200 /api/events\n    ${tally.non200.slice(0, 20).join('\n    ')}`);
  if (tally.misaligned.length) console.log(`  misaligned results\n    ${tally.misaligned.slice(0, 20).join('\n    ')}`);

  const checks: [string, boolean][] = [
    [`sessions created === --sessions (${tally.sessionsCreated} / ${options.sessions})`, tally.sessionsCreated === options.sessions],
    [`no session API failures (${tally.failures.length})`, tally.failures.length === 0],
    [`every /api/events response was HTTP 200 (${tally.non200.length} not)`, tally.non200.length === 0],
    [`one result per item, in input order (${tally.misaligned.length} batches misaligned)`, tally.misaligned.length === 0],
    [
      `accepted + duplicate + rejected === sent (${tally.accepted} + ${tally.duplicate} + ${rejectedTotal} = ${tally.accepted + tally.duplicate + rejectedTotal} / ${tally.sent})`,
      tally.accepted + tally.duplicate + rejectedTotal === tally.sent,
    ],
    [
      `verbatim resend produced 0 accepted (${tally.resend.accepted}), all duplicate or originally-rejected (${tally.resend.unexpected} unexpected)`,
      tally.resend.done && tally.resend.accepted === 0 && tally.resend.unexpected === 0,
    ],
    [
      `rejected invalid_shape >= injected invalid (${tally.rejected.get('invalid_shape')} >= ${tally.injectedInvalid})`,
      (tally.rejected.get('invalid_shape') ?? 0) >= tally.injectedInvalid,
    ],
    [`rejected server_only_event >= 1 (${tally.rejected.get('server_only_event')})`, (tally.rejected.get('server_only_event') ?? 0) >= 1],
    [`duplicate >= injected duplicates (${tally.duplicate} >= ${tally.injectedDuplicates})`, tally.duplicate >= tally.injectedDuplicates],
  ];

  console.log('\nInvariants');
  for (const [label, ok] of checks) console.log(`  ${ok ? 'PASS' : 'FAIL'}  ${label}`);
  const failed = checks.filter(([, ok]) => !ok).length;
  console.log(failed ? `\nFAIL: ${failed} invariant(s) violated` : '\nPASS: all invariants hold');
  process.exit(failed ? 1 : 0);
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  await main();
}
